We are using FIMO from the MEME Suite. It is installed as a Docker container and can be run in a specific directory with

docker run -v "$(pwd)":/home/meme -d memesuite/memesuite:latest

FIMO can then be run with in that container.

fimo --oc ./fimo_output --thresh 0.0001 Ray2013_rbp_Homo_sapiens.dna_encoded.meme single_designs.fa
fimo --oc ./fimo_output_mirna_targets --thresh 0.005 Ray2013_rbp_Homo_sapiens.dna_encoded.meme mirna_targets.fa

In [2]:
import pandas as pd
import os
import numpy
import scipy.stats as stats

## generate fasta file

In [3]:
# get mirbase
mirbase = pd.read_csv("../microrna_data/mirbase_extended.csv", index_col=0)

# get inserted designs
inserted_designs_1 = pd.read_csv("../design_files/inserted_designs/1_mirna_full_single_high_conf_inserted.csv", index_col=0)
inserted_designs_2 = pd.read_csv("../design_files/inserted_designs/2_mirna_full_single_low_conf_mirgenedb_inserted.csv", index_col=0)
inserted_designs = pd.concat([inserted_designs_1, inserted_designs_2])
inserted_designs = inserted_designs.set_index("miRNA1")

In [4]:
# save these as a fasta file
output_folder = "../FIMO"

with open(os.path.join(output_folder, "single_designs.fa"), "w") as f:
    for mirna in inserted_designs.index:
        f.write(f">{mirna}\n")
        f.write(f"{inserted_designs.loc[mirna, 'seq']}\n")
        
with open(os.path.join(output_folder, "mirna_targets.fa"), "w") as f:
    for mirna in mirbase.index:
        f.write(f">{mirna}\n")
        f.write(f"{mirbase.loc[mirna, 'target']}\n")

In [5]:
high_stability_mirnas = ['hsa-miR-365a-3p', 'hsa-miR-6802-3p', 'hsa-miR-3180-3p',
       'hsa-miR-582-5p', 'hsa-miR-197-3p', 'hsa-miR-9-3p',
       'hsa-miR-199a-5p', 'hsa-miR-342-3p', 'hsa-miR-340-5p',
       'hsa-miR-574-3p', 'hsa-miR-937-5p', 'hsa-miR-664b-3p',
       'hsa-miR-6791-5p', 'hsa-miR-3663-3p', 'hsa-miR-885-5p']
with open(os.path.join(output_folder, "high_stability_mirnas.fa"), "w") as f:
    for mirna in high_stability_mirnas:
        f.write(f">{mirna}\n")
        f.write(f"{mirbase.loc[mirna, 'target']}\n")

## Run FIMO

## Read in the resulting file

In [5]:
input_file = os.path.join(output_folder, "fimo_output_mirna_targets/fimo.tsv")
df_fimo = pd.read_csv(input_file, sep="\t")
#df_fimo.set_index("sequence_name", inplace=True)
df_fimo

,motif_id,motif_alt_id,sequence_name,start,stop,strand,score,p-value,q-value,matched_sequence
0,RNCMPT00072,SRSF2,hsa-miR-1825,3.0,10.0,+,11.71950,0.000012,0.0782,AGGAGAGG
1,RNCMPT00072,SRSF2,hsa-miR-6882-3p,9.0,16.0,+,11.71950,0.000012,0.0782,AGGAGAGG
2,RNCMPT00072,SRSF2,hsa-miR-483-3p,9.0,16.0,+,11.71950,0.000012,0.0782,AGGAGAGG
3,RNCMPT00072,SRSF2,hsa-miR-7109-3p,10.0,17.0,+,11.71950,0.000012,0.0782,AGGAGAGG
4,RNCMPT00072,SRSF2,hsa-miR-6823-3p,10.0,17.0,+,11.71950,0.000012,0.0782,AGGAGAGG
...,...,...,...,...,...,...,...,...,...,...
6289,RNCMPT00268,PTBP1,hsa-miR-1282,6.0,12.0,-,8.72789,0.000499,0.7340,TTTTTCT
6290,RNCMPT00268,PTBP1,hsa-miR-6832-3p,11.0,17.0,-,8.72789,0.000499,0.7340,TTTTTCT
6291,# FIMO (Find Individual Motif Occurrences): Ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6292,# The format of this file is described at http...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6293,# fimo --oc ./fimo_output_mirna_targets --thre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# load the deviation df
df_deviation = pd.read_csv("../outputs/3_fitting/combined_dataset/combined_dataset_deviation.csv", index_col=0)
df_deviation

,HEK293T,HeLa,SKNSH,MCF7,HUH7,A549,HaCaT,JEG3,Tera1,PC3
hsa-let-7a-3p,-0.014851,0.003325,-0.020337,0.026364,-0.022338,-0.001909,0.006001,-0.019002,-0.084692,0.064567
hsa-let-7a-5p,-0.045445,0.018718,0.187174,-0.255312,0.033477,-0.049017,-0.058934,0.142148,-0.119159,0.197415
hsa-let-7b-3p,-0.031168,-0.045728,-0.046873,-0.038836,-0.034085,-0.022010,-0.102620,-0.061370,-0.058173,-0.016885
hsa-let-7c-3p,0.009192,-0.011490,0.013342,-0.013654,0.010554,0.009805,-0.051490,-0.072508,-0.064482,-0.034341
hsa-let-7d-3p,0.029086,-0.147397,-0.071523,-0.140335,-0.000995,-0.048796,-0.224221,-0.014405,-0.031357,-0.185445
...,...,...,...,...,...,...,...,...,...,...
hsa-miR-892b,-0.020141,0.000671,0.000018,0.036663,-0.024445,-0.027480,-0.011594,-0.018966,0.006337,-0.017020
hsa-miR-934,-0.041725,-0.033330,-0.006969,-0.001306,-0.069197,-0.057521,-0.042116,-0.076929,-0.078366,-0.049338
hsa-miR-935,-0.011195,0.070744,-0.012866,0.024961,-0.004617,-0.004408,-0.027298,-0.018127,-0.028768,0.023749
hsa-miR-944,0.023993,0.024915,-0.027897,0.025565,0.041143,0.056149,0.034648,0.082210,0.071552,0.016295
hsa-miR-95-5p,0.005622,0.000998,0.019834,0.012796,0.023238,0.047276,0.016849,-0.009304,-0.052774,0.037335

In [28]:
# binarize FIMO by the miRNA
binary_fimo = df_fimo.groupby(['sequence_name', 'motif_alt_id']).size().unstack(fill_value=0)
binary_fimo[binary_fimo > 0] = 1  # Convert counts to binary

# Align binary_fimo to df_deviation
binary_fimo = binary_fimo.reindex(df_deviation.index).fillna(0)

In [53]:
# Initialize a DataFrame to store results
results = pd.DataFrame(columns=['Motif', 'Cell Line', 'Correlation Coefficient', 'P-value'])

# Iterate over each motif in binary_fimo
for motif in binary_fimo.columns:
    # Iterate over each cell line in df_deviation
    for cell_line in df_deviation.columns:
        # calculate Pearson correlation and p-value
        df_deviation_cell_line = df_deviation[cell_line].dropna()
        corr, p_value = stats.pearsonr(binary_fimo.loc[df_deviation_cell_line.index, motif], df_deviation_cell_line)

        # Append results
        new_row = pd.DataFrame({
            'Motif': motif,
            'Cell Line': cell_line,
            'Correlation Coefficient': corr,
            'P-value': p_value
        }, index=[motif+"_"+cell_line])
        
        results = pd.concat([results, new_row])
       
significant_results = results[results['P-value'] < 0.05]
significant_results = significant_results.sort_values(by="P-value", ascending=True)
print(significant_results)

C:\Users\loesi\AppData\Local\Temp\ipykernel_11004\3130456616.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, new_row])
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))

<bound method DataFrame.sort_values of                    Motif Cell Line  Correlation Coefficient       P-value
ZNF638_MCF7       ZNF638      MCF7                 0.190442  1.160485e-09
YBX1_SKNSH          YBX1     SKNSH                 0.157476  4.972408e-07
PTBP1_Tera1        PTBP1     Tera1                -0.141989  6.225189e-06
PTBP1_SKNSH        PTBP1     SKNSH                -0.136746  1.307643e-05
KHDRBS1_HeLa     KHDRBS1      HeLa                -0.132556  2.514072e-05
ZNF638_HUH7       ZNF638      HUH7                 0.108219  5.671970e-04
KHDRBS1_HUH7     KHDRBS1      HUH7                -0.101638  1.211837e-03
KHDRBS1_MCF7     KHDRBS1      MCF7                -0.095050  2.558636e-03
SNRPA_MCF7         SNRPA      MCF7                -0.088636  4.924104e-03
KHDRBS1_SKNSH    KHDRBS1     SKNSH                -0.088013  5.147101e-03
KHDRBS1_A549     KHDRBS1      A549                -0.080560  1.050709e-02
PABPC5_JEG3       PABPC5      JEG3                 0.080445  1.101314e-02
SNRPA_HEK293T      SNRPA   HEK293T                -0.079828  1.111281e-02
PTBP1_HEK293T      PTBP1   HEK293T                -0.079567  1.137991e-02
DAZAP1_HEK293T    DAZAP1   HEK293T                 0.079237  1.172603e-02
SNRNP70_HEK293T  SNRNP70   HEK293T                 0.076698  1.471680e-02
YBX1_HaCaT          YBX1     HaCaT                 0.077108  1.477960e-02
RBM6_HUH7           RBM6      HUH7                -0.073108  2.008334e-02
SNRPA_HUH7         SNRPA      HUH7                -0.072673  2.083780e-02
ENOX1_MCF7         ENOX1      MCF7                 0.071683  2.305181e-02
FMR1_A549           FMR1      A549                -0.069328  2.773423e-02
FMR1_HUH7           FMR1      HUH7                -0.068859  2.857207e-02
RBM6_MCF7           RBM6      MCF7                -0.068183  3.066852e-02
YBX1_A549           YBX1      A549                 0.067625  3.180654e-02
DAZAP1_MCF7       DAZAP1      MCF7                 0.067674  3.193902e-02
SRSF9_A549         SRSF9      A549                 0.066566  3.459019e-02
YBX1_MCF7           YBX1      MCF7                -0.066034  3.634206e-02
KHDRBS1_HaCaT    KHDRBS1     HaCaT                -0.066200  3.643474e-02
SNRNP70_HUH7     SNRNP70      HUH7                 0.065127  3.841350e-02
KHDRBS1_HEK293T  KHDRBS1   HEK293T                -0.064567  4.011142e-02
PTBP1_MCF7         PTBP1      MCF7                -0.063729  4.339840e-02
RBM6_HaCaT          RBM6     HaCaT                -0.063614  4.441323e-02
HNRNPH2_HUH7     HNRNPH2      HUH7                -0.062870  4.566032e-02>

In [59]:
df_deviation['mean_deviation'] = df_deviation.fillna(0).mean(axis=1)

# Initialize a DataFrame to store results
results = pd.DataFrame(columns=['Motif', 'Correlation Coefficient', 'P-value'])

# Iterate over each motif in binary_fimo
for motif in binary_fimo.columns:
    # Calculate Pearson correlation and p-value between the motif and the aggregate deviation
    corr, p_value = stats.pearsonr(binary_fimo[motif], df_deviation['mean_deviation'])

    # Append results
    new_row = pd.DataFrame({
        'Motif': motif,
        'Correlation Coefficient': corr,
        'P-value': p_value
    }, index=[motif])
    
    results = pd.concat([results, new_row])

# Optionally, filter results to show only statistically significant correlations
significant_results = results[results['P-value'] < 0.05]
significant_results = significant_results.sort_values(by="P-value", ascending=True)
print(significant_results)

           Motif  Correlation Coefficient   P-value
KHDRBS1  KHDRBS1                -0.086278  0.006050
PTBP1      PTBP1                -0.078573  0.012451
ZNF638    ZNF638                 0.070279  0.025443

C:\Users\loesi\AppData\Local\Temp\ipykernel_11004\3769256464.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  results = pd.concat([results, new_row])
c:\Users\loesi\anaconda3\envs\Bio\Lib\site-packages\scipy\stats\_stats_py.py:4781: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  warnings.warn(stats.ConstantInputWarning(msg))

In [63]:
for RBP in significant_results.index:
    RBP_mirnas = df_fimo[df_fimo["motif_alt_id"] == RBP]["sequence_name"]
    print(RBP)
    print(df_deviation.loc[RBP_mirnas, :])

KHDRBS1
                 HEK293T      HeLa     SKNSH      MCF7      HUH7      A549  \
hsa-miR-590-5p -0.170999 -0.303581 -0.226934 -0.235054 -0.215432 -0.197553

                   HaCaT      JEG3     Tera1       PC3  mean_deviation
hsa-miR-590-5p -0.168665 -0.126686 -0.058606 -0.117463       -0.182097
PTBP1
                   HEK293T      HeLa     SKNSH      MCF7      HUH7      A549  \
hsa-miR-580-5p   -0.033675  0.011420 -0.042002  0.019259  0.038394  0.046839
hsa-miR-518c-5p  -0.012345  0.031068  0.011084  0.025521 -0.048714  0.002491
hsa-miR-526b-5p  -0.001271 -0.003798  0.000932  0.040436 -0.036315 -0.008425
hsa-miR-520a-5p  -0.012686  0.012034 -0.007832  0.016401  0.028335  0.028158
hsa-miR-518f-5p  -0.016566  0.007206  0.006028  0.034310 -0.022454  0.019048
hsa-miR-548x-3p   0.022763  0.028153  0.028313  0.000594  0.023828  0.041227
hsa-miR-525-5p   -0.054922 -0.035622 -0.016691  0.021360 -0.057648 -0.020439
hsa-miR-520g-5p  -0.033884  0.007404  0.001641  0.000935 -0.017936 -0.000568
hsa-miR-520e-3p  -0.083231 -0.066889 -0.152759 -0.007629 -0.033301  0.011834
hsa-miR-372-3p   -0.006331  0.023882 -0.062600  0.010257  0.042715  0.032446
hsa-miR-520a-3p  -0.033072 -0.056762 -0.077970 -0.027123 -0.019267 -0.005343
hsa-miR-520d-3p  -0.107683 -0.057788 -0.152554 -0.027345 -0.062825 -0.011458
hsa-miR-519c-3p  -0.046109 -0.024894 -0.099611  0.031540 -0.002768  0.009275
hsa-miR-520c-3p  -0.073066 -0.058825 -0.148688  0.004741 -0.002864  0.009591
hsa-miR-520b-3p  -0.072965 -0.059141 -0.148497  0.004650 -0.002752  0.009816
hsa-miR-519b-3p  -0.069011 -0.058626 -0.113914 -0.014309 -0.028107  0.015119
hsa-miR-148a-5p   0.020656  0.021348 -0.024109  0.026392 -0.000887  0.021876
hsa-miR-627-5p    0.001345 -0.018551 -0.010209 -0.033273  0.020596 -0.021521
hsa-miR-320a-3p  -0.219093 -0.205738 -0.222336 -0.189730 -0.152211 -0.234606
hsa-miR-548av-5p  0.017135  0.040246 -0.003053  0.005970  0.020198  0.038080
hsa-miR-548ar-5p -0.016899 -0.003880 -0.038435 -0.033231  0.020424  0.014368
hsa-miR-548as-5p  0.000271  0.010775 -0.022518 -0.037096  0.025395  0.019798
hsa-miR-548am-5p -0.013422  0.007803 -0.036006 -0.048508  0.011183 -0.002025
hsa-miR-548ap-5p  0.014751  0.014138 -0.032204 -0.042409  0.009041 -0.001650
hsa-miR-548ay-5p  0.023683  0.034089 -0.016244 -0.013515  0.051998  0.022229
hsa-miR-548b-5p   0.036694  0.032159 -0.005329 -0.034932  0.024353  0.014530
hsa-miR-548d-5p   0.026137  0.035675 -0.015555 -0.012302  0.058963  0.023511
hsa-miR-548h-5p   0.020717  0.038174 -0.015287  0.003308  0.010042  0.011379
hsa-miR-548j-5p  -0.006199 -0.001041 -0.035726 -0.035761  0.020293  0.009892
hsa-miR-548at-5p  0.023127  0.053947 -0.050540 -0.017090  0.025967  0.027539
hsa-miR-548a-5p   0.035828  0.041402 -0.012752 -0.022885  0.046450  0.019945
hsa-miR-320b     -0.306878 -0.402616 -0.368938 -0.291216 -0.279016 -0.414957
hsa-miR-320c     -0.467814 -0.492221 -0.555858 -0.421527 -0.371269 -0.502825
hsa-miR-627-3p   -0.006993  0.015382 -0.005997 -0.013513 -0.003474 -0.000911

                     HaCaT      JEG3     Tera1       PC3  mean_deviation
hsa-miR-580-5p    0.004684  0.003072  0.013053  0.017156        0.007820
hsa-miR-518c-5p   0.023539  0.094418 -0.023245  0.034571        0.013839
hsa-miR-526b-5p  -0.002118  0.111855 -0.000982  0.001434        0.010175
hsa-miR-520a-5p   0.004667 -0.159014 -0.129275  0.004187       -0.021503
hsa-miR-518f-5p   0.015415       NaN  0.004513 -0.004700        0.004323
hsa-miR-548x-3p   0.011784 -0.006025 -0.017033  0.027614        0.016122
hsa-miR-525-5p   -0.035143  0.007282 -0.049027 -0.019827       -0.026068
hsa-miR-520g-5p   0.018897 -0.016163  0.015658  0.015831       -0.000819
hsa-miR-520e-3p  -0.024918       NaN       NaN -0.039712       -0.040562
hsa-miR-372-3p    0.009525  0.194523 -0.179045  0.016958        0.008233
hsa-miR-520a-3p  -0.037006       NaN -0.301038 -0.022448       -0.058589
hsa-miR-520d-3p  -0.024262 -0.160036 -0.392644 -0.045883       -0.104248
hsa-miR-519c-3p  -0.007707  0.011962 -0.296627 -0.018186       -0.044312
hsa-miR-520c-3p  -0.008014  0.054389 -0.496088 -0.016816       -0.073564
hsa-miR-520b-3p  -0.008217       NaN -0.498728 -0.016501       -0.080034
hsa-miR-519b-3p  -0.023216 -0.023877 -0.391670 -0.025656       -0.073327
hsa-miR-148a-5p  -0.033177 -0.074179 -0.046011 -0.000870       -0.008896
hsa-miR-627-5p   -0.009915 -0.026447 -0.024721 -0.002504       -0.012520
hsa-miR-320a-3p  -0.332376 -0.054966 -0.300987 -0.229205       -0.214125
hsa-miR-548av-5p  0.036080  0.023671 -0.016491  0.034969        0.019681
hsa-miR-548ar-5p  0.006360  0.012560 -0.046690 -0.002506       -0.008793
hsa-miR-548as-5p -0.001440  0.013129 -0.021647  0.011002       -0.000233
hsa-miR-548am-5p -0.015501  0.007977 -0.025919  0.010904       -0.010351
hsa-miR-548ap-5p  0.005077 -0.022654 -0.056076  0.012733       -0.009925
hsa-miR-548ay-5p  0.021855  0.020054 -0.007604  0.046168        0.018271
hsa-miR-548b-5p   0.028725  0.003893 -0.017874  0.031859        0.011408
hsa-miR-548d-5p   0.023304  0.021186 -0.006729  0.048383        0.020257
hsa-miR-548h-5p   0.013152 -0.033495 -0.043655  0.018895        0.002323
hsa-miR-548j-5p  -0.011243  0.010660  0.002330 -0.015381       -0.006218
hsa-miR-548at-5p  0.021703  0.045562  0.007422  0.029303        0.016694
hsa-miR-548a-5p   0.034643  0.069122  0.024465  0.014866        0.025108
hsa-miR-320b     -0.432898 -0.042178 -0.304765 -0.416823       -0.326029
hsa-miR-320c     -0.557504 -0.188922 -0.592306 -0.504302       -0.465455
hsa-miR-627-3p   -0.017626 -0.043351 -0.031199  0.011423       -0.009626
ZNF638
                  HEK293T      HeLa     SKNSH      MCF7      HUH7      A549  \
hsa-miR-208b-3p  0.052368  0.021159  0.030077 -0.028035  0.050602  0.052587
hsa-miR-93-5p    0.114465  0.093679  0.160259  0.684916  0.223918  0.134414
hsa-miR-382-5p   0.035607  0.025821 -0.006871  0.018807  0.067772  0.020453
hsa-miR-375-3p   0.043970  0.019013 -0.100676  0.218646  0.033438 -0.040629

                    HaCaT      JEG3     Tera1       PC3  mean_deviation
hsa-miR-208b-3p  0.026914  0.005110  0.019017  0.029268        0.025907
hsa-miR-93-5p    0.092668 -0.207476 -0.048368  0.097735        0.134621
hsa-miR-382-5p   0.025604  0.018752 -0.011698  0.027013        0.022126
hsa-miR-375-3p  -0.018017  0.009964 -0.027082  0.078259        0.021689